// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Iec61499Arrayspezifikationen1.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_IEC61499ARRAYSPEZIFIKATIONEN1_H_
#define _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_IEC61499ARRAYSPEZIFIKATIONEN1_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(IEC61499ARRAYSPEZIFIKATIONEN1_SOURCE)
#define IEC61499ARRAYSPEZIFIKATIONEN1_DllAPI __declspec( dllexport )
#else
#define IEC61499ARRAYSPEZIFIKATIONEN1_DllAPI __declspec( dllimport )
#endif // IEC61499ARRAYSPEZIFIKATIONEN1_SOURCE
#else
#define IEC61499ARRAYSPEZIFIKATIONEN1_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define IEC61499ARRAYSPEZIFIKATIONEN1_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace conversion_tests {
    namespace msg {
        typedef std::array<bool, 3> boolean__3;
        /*!
         * @brief This class represents the structure Iec61499Arrayspezifikationen1 defined by the user in the IDL file.
         * @ingroup Iec61499Arrayspezifikationen1
         */
        class Iec61499Arrayspezifikationen1
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport Iec61499Arrayspezifikationen1();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~Iec61499Arrayspezifikationen1();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object conversion_tests::msg::Iec61499Arrayspezifikationen1 that will be copied.
             */
            eProsima_user_DllExport Iec61499Arrayspezifikationen1(
                    const Iec61499Arrayspezifikationen1& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object conversion_tests::msg::Iec61499Arrayspezifikationen1 that will be copied.
             */
            eProsima_user_DllExport Iec61499Arrayspezifikationen1(
                    Iec61499Arrayspezifikationen1&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object conversion_tests::msg::Iec61499Arrayspezifikationen1 that will be copied.
             */
            eProsima_user_DllExport Iec61499Arrayspezifikationen1& operator =(
                    const Iec61499Arrayspezifikationen1& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object conversion_tests::msg::Iec61499Arrayspezifikationen1 that will be copied.
             */
            eProsima_user_DllExport Iec61499Arrayspezifikationen1& operator =(
                    Iec61499Arrayspezifikationen1&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x conversion_tests::msg::Iec61499Arrayspezifikationen1 object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const Iec61499Arrayspezifikationen1& x) const;

            /*!
             * @brief Comparison operator.
             * @param x conversion_tests::msg::Iec61499Arrayspezifikationen1 object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const Iec61499Arrayspezifikationen1& x) const;

            /*!
             * @brief This function copies the value in member static_array_with_capacity
             * @param _static_array_with_capacity New value to be copied in member static_array_with_capacity
             */
            eProsima_user_DllExport void static_array_with_capacity(
                    const conversion_tests::msg::boolean__3& _static_array_with_capacity);

            /*!
             * @brief This function moves the value in member static_array_with_capacity
             * @param _static_array_with_capacity New value to be moved in member static_array_with_capacity
             */
            eProsima_user_DllExport void static_array_with_capacity(
                    conversion_tests::msg::boolean__3&& _static_array_with_capacity);

            /*!
             * @brief This function returns a constant reference to member static_array_with_capacity
             * @return Constant reference to member static_array_with_capacity
             */
            eProsima_user_DllExport const conversion_tests::msg::boolean__3& static_array_with_capacity() const;

            /*!
             * @brief This function returns a reference to member static_array_with_capacity
             * @return Reference to member static_array_with_capacity
             */
            eProsima_user_DllExport conversion_tests::msg::boolean__3& static_array_with_capacity();
            /*!
             * @brief This function copies the value in member static_array_with_indexation
             * @param _static_array_with_indexation New value to be copied in member static_array_with_indexation
             */
            eProsima_user_DllExport void static_array_with_indexation(
                    const conversion_tests::msg::boolean__3& _static_array_with_indexation);

            /*!
             * @brief This function moves the value in member static_array_with_indexation
             * @param _static_array_with_indexation New value to be moved in member static_array_with_indexation
             */
            eProsima_user_DllExport void static_array_with_indexation(
                    conversion_tests::msg::boolean__3&& _static_array_with_indexation);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation
             * @return Constant reference to member static_array_with_indexation
             */
            eProsima_user_DllExport const conversion_tests::msg::boolean__3& static_array_with_indexation() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation
             * @return Reference to member static_array_with_indexation
             */
            eProsima_user_DllExport conversion_tests::msg::boolean__3& static_array_with_indexation();

            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const conversion_tests::msg::Iec61499Arrayspezifikationen1& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            conversion_tests::msg::boolean__3 m_static_array_with_capacity;
            conversion_tests::msg::boolean__3 m_static_array_with_indexation;

        };
    } // namespace msg
} // namespace conversion_tests

#endif // _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_IEC61499ARRAYSPEZIFIKATIONEN1_H_

