// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Iec61499Arrayspezifikationen2.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_IEC61499ARRAYSPEZIFIKATIONEN2_H_
#define _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_IEC61499ARRAYSPEZIFIKATIONEN2_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(IEC61499ARRAYSPEZIFIKATIONEN2_SOURCE)
#define IEC61499ARRAYSPEZIFIKATIONEN2_DllAPI __declspec( dllexport )
#else
#define IEC61499ARRAYSPEZIFIKATIONEN2_DllAPI __declspec( dllimport )
#endif // IEC61499ARRAYSPEZIFIKATIONEN2_SOURCE
#else
#define IEC61499ARRAYSPEZIFIKATIONEN2_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define IEC61499ARRAYSPEZIFIKATIONEN2_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace conversion_tests {
    namespace msg {
        typedef std::array<bool, 2> boolean__2;
        typedef std::array<uint8_t, 2> octet__2;
        typedef std::array<uint16_t, 2> uint16__2;
        typedef std::array<uint32_t, 2> uint32__2;
        typedef std::array<uint64_t, 2> uint64__2;
        typedef std::array<int8_t, 2> int8__2;
        typedef std::array<int16_t, 2> int16__2;
        typedef std::array<int32_t, 2> int32__2;
        typedef std::array<int64_t, 2> int64__2;
        typedef std::array<uint8_t, 2> uint8__2;
        typedef std::array<float, 2> float__2;
        typedef std::array<double, 2> double__2;
        typedef std::array<std::string, 2> string__2;
        typedef std::array<std::wstring, 2> wstring__2;
        /*!
         * @brief This class represents the structure Iec61499Arrayspezifikationen2 defined by the user in the IDL file.
         * @ingroup Iec61499Arrayspezifikationen2
         */
        class Iec61499Arrayspezifikationen2
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport Iec61499Arrayspezifikationen2();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~Iec61499Arrayspezifikationen2();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object conversion_tests::msg::Iec61499Arrayspezifikationen2 that will be copied.
             */
            eProsima_user_DllExport Iec61499Arrayspezifikationen2(
                    const Iec61499Arrayspezifikationen2& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object conversion_tests::msg::Iec61499Arrayspezifikationen2 that will be copied.
             */
            eProsima_user_DllExport Iec61499Arrayspezifikationen2(
                    Iec61499Arrayspezifikationen2&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object conversion_tests::msg::Iec61499Arrayspezifikationen2 that will be copied.
             */
            eProsima_user_DllExport Iec61499Arrayspezifikationen2& operator =(
                    const Iec61499Arrayspezifikationen2& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object conversion_tests::msg::Iec61499Arrayspezifikationen2 that will be copied.
             */
            eProsima_user_DllExport Iec61499Arrayspezifikationen2& operator =(
                    Iec61499Arrayspezifikationen2&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x conversion_tests::msg::Iec61499Arrayspezifikationen2 object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const Iec61499Arrayspezifikationen2& x) const;

            /*!
             * @brief Comparison operator.
             * @param x conversion_tests::msg::Iec61499Arrayspezifikationen2 object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const Iec61499Arrayspezifikationen2& x) const;

            /*!
             * @brief This function copies the value in member static_array_with_indexation1
             * @param _static_array_with_indexation1 New value to be copied in member static_array_with_indexation1
             */
            eProsima_user_DllExport void static_array_with_indexation1(
                    const conversion_tests::msg::boolean__2& _static_array_with_indexation1);

            /*!
             * @brief This function moves the value in member static_array_with_indexation1
             * @param _static_array_with_indexation1 New value to be moved in member static_array_with_indexation1
             */
            eProsima_user_DllExport void static_array_with_indexation1(
                    conversion_tests::msg::boolean__2&& _static_array_with_indexation1);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation1
             * @return Constant reference to member static_array_with_indexation1
             */
            eProsima_user_DllExport const conversion_tests::msg::boolean__2& static_array_with_indexation1() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation1
             * @return Reference to member static_array_with_indexation1
             */
            eProsima_user_DllExport conversion_tests::msg::boolean__2& static_array_with_indexation1();
            /*!
             * @brief This function copies the value in member static_array_with_indexation2
             * @param _static_array_with_indexation2 New value to be copied in member static_array_with_indexation2
             */
            eProsima_user_DllExport void static_array_with_indexation2(
                    const conversion_tests::msg::octet__2& _static_array_with_indexation2);

            /*!
             * @brief This function moves the value in member static_array_with_indexation2
             * @param _static_array_with_indexation2 New value to be moved in member static_array_with_indexation2
             */
            eProsima_user_DllExport void static_array_with_indexation2(
                    conversion_tests::msg::octet__2&& _static_array_with_indexation2);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation2
             * @return Constant reference to member static_array_with_indexation2
             */
            eProsima_user_DllExport const conversion_tests::msg::octet__2& static_array_with_indexation2() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation2
             * @return Reference to member static_array_with_indexation2
             */
            eProsima_user_DllExport conversion_tests::msg::octet__2& static_array_with_indexation2();
            /*!
             * @brief This function copies the value in member static_array_with_indexation3
             * @param _static_array_with_indexation3 New value to be copied in member static_array_with_indexation3
             */
            eProsima_user_DllExport void static_array_with_indexation3(
                    const conversion_tests::msg::uint16__2& _static_array_with_indexation3);

            /*!
             * @brief This function moves the value in member static_array_with_indexation3
             * @param _static_array_with_indexation3 New value to be moved in member static_array_with_indexation3
             */
            eProsima_user_DllExport void static_array_with_indexation3(
                    conversion_tests::msg::uint16__2&& _static_array_with_indexation3);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation3
             * @return Constant reference to member static_array_with_indexation3
             */
            eProsima_user_DllExport const conversion_tests::msg::uint16__2& static_array_with_indexation3() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation3
             * @return Reference to member static_array_with_indexation3
             */
            eProsima_user_DllExport conversion_tests::msg::uint16__2& static_array_with_indexation3();
            /*!
             * @brief This function copies the value in member static_array_with_indexation4
             * @param _static_array_with_indexation4 New value to be copied in member static_array_with_indexation4
             */
            eProsima_user_DllExport void static_array_with_indexation4(
                    const conversion_tests::msg::uint32__2& _static_array_with_indexation4);

            /*!
             * @brief This function moves the value in member static_array_with_indexation4
             * @param _static_array_with_indexation4 New value to be moved in member static_array_with_indexation4
             */
            eProsima_user_DllExport void static_array_with_indexation4(
                    conversion_tests::msg::uint32__2&& _static_array_with_indexation4);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation4
             * @return Constant reference to member static_array_with_indexation4
             */
            eProsima_user_DllExport const conversion_tests::msg::uint32__2& static_array_with_indexation4() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation4
             * @return Reference to member static_array_with_indexation4
             */
            eProsima_user_DllExport conversion_tests::msg::uint32__2& static_array_with_indexation4();
            /*!
             * @brief This function copies the value in member static_array_with_indexation5
             * @param _static_array_with_indexation5 New value to be copied in member static_array_with_indexation5
             */
            eProsima_user_DllExport void static_array_with_indexation5(
                    const conversion_tests::msg::uint64__2& _static_array_with_indexation5);

            /*!
             * @brief This function moves the value in member static_array_with_indexation5
             * @param _static_array_with_indexation5 New value to be moved in member static_array_with_indexation5
             */
            eProsima_user_DllExport void static_array_with_indexation5(
                    conversion_tests::msg::uint64__2&& _static_array_with_indexation5);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation5
             * @return Constant reference to member static_array_with_indexation5
             */
            eProsima_user_DllExport const conversion_tests::msg::uint64__2& static_array_with_indexation5() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation5
             * @return Reference to member static_array_with_indexation5
             */
            eProsima_user_DllExport conversion_tests::msg::uint64__2& static_array_with_indexation5();
            /*!
             * @brief This function copies the value in member static_array_with_indexation6
             * @param _static_array_with_indexation6 New value to be copied in member static_array_with_indexation6
             */
            eProsima_user_DllExport void static_array_with_indexation6(
                    const conversion_tests::msg::int8__2& _static_array_with_indexation6);

            /*!
             * @brief This function moves the value in member static_array_with_indexation6
             * @param _static_array_with_indexation6 New value to be moved in member static_array_with_indexation6
             */
            eProsima_user_DllExport void static_array_with_indexation6(
                    conversion_tests::msg::int8__2&& _static_array_with_indexation6);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation6
             * @return Constant reference to member static_array_with_indexation6
             */
            eProsima_user_DllExport const conversion_tests::msg::int8__2& static_array_with_indexation6() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation6
             * @return Reference to member static_array_with_indexation6
             */
            eProsima_user_DllExport conversion_tests::msg::int8__2& static_array_with_indexation6();
            /*!
             * @brief This function copies the value in member static_array_with_indexation7
             * @param _static_array_with_indexation7 New value to be copied in member static_array_with_indexation7
             */
            eProsima_user_DllExport void static_array_with_indexation7(
                    const conversion_tests::msg::int16__2& _static_array_with_indexation7);

            /*!
             * @brief This function moves the value in member static_array_with_indexation7
             * @param _static_array_with_indexation7 New value to be moved in member static_array_with_indexation7
             */
            eProsima_user_DllExport void static_array_with_indexation7(
                    conversion_tests::msg::int16__2&& _static_array_with_indexation7);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation7
             * @return Constant reference to member static_array_with_indexation7
             */
            eProsima_user_DllExport const conversion_tests::msg::int16__2& static_array_with_indexation7() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation7
             * @return Reference to member static_array_with_indexation7
             */
            eProsima_user_DllExport conversion_tests::msg::int16__2& static_array_with_indexation7();
            /*!
             * @brief This function copies the value in member static_array_with_indexation8
             * @param _static_array_with_indexation8 New value to be copied in member static_array_with_indexation8
             */
            eProsima_user_DllExport void static_array_with_indexation8(
                    const conversion_tests::msg::int32__2& _static_array_with_indexation8);

            /*!
             * @brief This function moves the value in member static_array_with_indexation8
             * @param _static_array_with_indexation8 New value to be moved in member static_array_with_indexation8
             */
            eProsima_user_DllExport void static_array_with_indexation8(
                    conversion_tests::msg::int32__2&& _static_array_with_indexation8);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation8
             * @return Constant reference to member static_array_with_indexation8
             */
            eProsima_user_DllExport const conversion_tests::msg::int32__2& static_array_with_indexation8() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation8
             * @return Reference to member static_array_with_indexation8
             */
            eProsima_user_DllExport conversion_tests::msg::int32__2& static_array_with_indexation8();
            /*!
             * @brief This function copies the value in member static_array_with_indexation9
             * @param _static_array_with_indexation9 New value to be copied in member static_array_with_indexation9
             */
            eProsima_user_DllExport void static_array_with_indexation9(
                    const conversion_tests::msg::int64__2& _static_array_with_indexation9);

            /*!
             * @brief This function moves the value in member static_array_with_indexation9
             * @param _static_array_with_indexation9 New value to be moved in member static_array_with_indexation9
             */
            eProsima_user_DllExport void static_array_with_indexation9(
                    conversion_tests::msg::int64__2&& _static_array_with_indexation9);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation9
             * @return Constant reference to member static_array_with_indexation9
             */
            eProsima_user_DllExport const conversion_tests::msg::int64__2& static_array_with_indexation9() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation9
             * @return Reference to member static_array_with_indexation9
             */
            eProsima_user_DllExport conversion_tests::msg::int64__2& static_array_with_indexation9();
            /*!
             * @brief This function copies the value in member static_array_with_indexation10
             * @param _static_array_with_indexation10 New value to be copied in member static_array_with_indexation10
             */
            eProsima_user_DllExport void static_array_with_indexation10(
                    const conversion_tests::msg::uint8__2& _static_array_with_indexation10);

            /*!
             * @brief This function moves the value in member static_array_with_indexation10
             * @param _static_array_with_indexation10 New value to be moved in member static_array_with_indexation10
             */
            eProsima_user_DllExport void static_array_with_indexation10(
                    conversion_tests::msg::uint8__2&& _static_array_with_indexation10);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation10
             * @return Constant reference to member static_array_with_indexation10
             */
            eProsima_user_DllExport const conversion_tests::msg::uint8__2& static_array_with_indexation10() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation10
             * @return Reference to member static_array_with_indexation10
             */
            eProsima_user_DllExport conversion_tests::msg::uint8__2& static_array_with_indexation10();
            /*!
             * @brief This function copies the value in member static_array_with_indexation11
             * @param _static_array_with_indexation11 New value to be copied in member static_array_with_indexation11
             */
            eProsima_user_DllExport void static_array_with_indexation11(
                    const conversion_tests::msg::uint16__2& _static_array_with_indexation11);

            /*!
             * @brief This function moves the value in member static_array_with_indexation11
             * @param _static_array_with_indexation11 New value to be moved in member static_array_with_indexation11
             */
            eProsima_user_DllExport void static_array_with_indexation11(
                    conversion_tests::msg::uint16__2&& _static_array_with_indexation11);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation11
             * @return Constant reference to member static_array_with_indexation11
             */
            eProsima_user_DllExport const conversion_tests::msg::uint16__2& static_array_with_indexation11() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation11
             * @return Reference to member static_array_with_indexation11
             */
            eProsima_user_DllExport conversion_tests::msg::uint16__2& static_array_with_indexation11();
            /*!
             * @brief This function copies the value in member static_array_with_indexation12
             * @param _static_array_with_indexation12 New value to be copied in member static_array_with_indexation12
             */
            eProsima_user_DllExport void static_array_with_indexation12(
                    const conversion_tests::msg::uint32__2& _static_array_with_indexation12);

            /*!
             * @brief This function moves the value in member static_array_with_indexation12
             * @param _static_array_with_indexation12 New value to be moved in member static_array_with_indexation12
             */
            eProsima_user_DllExport void static_array_with_indexation12(
                    conversion_tests::msg::uint32__2&& _static_array_with_indexation12);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation12
             * @return Constant reference to member static_array_with_indexation12
             */
            eProsima_user_DllExport const conversion_tests::msg::uint32__2& static_array_with_indexation12() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation12
             * @return Reference to member static_array_with_indexation12
             */
            eProsima_user_DllExport conversion_tests::msg::uint32__2& static_array_with_indexation12();
            /*!
             * @brief This function copies the value in member static_array_with_indexation13
             * @param _static_array_with_indexation13 New value to be copied in member static_array_with_indexation13
             */
            eProsima_user_DllExport void static_array_with_indexation13(
                    const conversion_tests::msg::uint64__2& _static_array_with_indexation13);

            /*!
             * @brief This function moves the value in member static_array_with_indexation13
             * @param _static_array_with_indexation13 New value to be moved in member static_array_with_indexation13
             */
            eProsima_user_DllExport void static_array_with_indexation13(
                    conversion_tests::msg::uint64__2&& _static_array_with_indexation13);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation13
             * @return Constant reference to member static_array_with_indexation13
             */
            eProsima_user_DllExport const conversion_tests::msg::uint64__2& static_array_with_indexation13() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation13
             * @return Reference to member static_array_with_indexation13
             */
            eProsima_user_DllExport conversion_tests::msg::uint64__2& static_array_with_indexation13();
            /*!
             * @brief This function copies the value in member static_array_with_indexation14
             * @param _static_array_with_indexation14 New value to be copied in member static_array_with_indexation14
             */
            eProsima_user_DllExport void static_array_with_indexation14(
                    const conversion_tests::msg::float__2& _static_array_with_indexation14);

            /*!
             * @brief This function moves the value in member static_array_with_indexation14
             * @param _static_array_with_indexation14 New value to be moved in member static_array_with_indexation14
             */
            eProsima_user_DllExport void static_array_with_indexation14(
                    conversion_tests::msg::float__2&& _static_array_with_indexation14);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation14
             * @return Constant reference to member static_array_with_indexation14
             */
            eProsima_user_DllExport const conversion_tests::msg::float__2& static_array_with_indexation14() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation14
             * @return Reference to member static_array_with_indexation14
             */
            eProsima_user_DllExport conversion_tests::msg::float__2& static_array_with_indexation14();
            /*!
             * @brief This function copies the value in member static_array_with_indexation15
             * @param _static_array_with_indexation15 New value to be copied in member static_array_with_indexation15
             */
            eProsima_user_DllExport void static_array_with_indexation15(
                    const conversion_tests::msg::double__2& _static_array_with_indexation15);

            /*!
             * @brief This function moves the value in member static_array_with_indexation15
             * @param _static_array_with_indexation15 New value to be moved in member static_array_with_indexation15
             */
            eProsima_user_DllExport void static_array_with_indexation15(
                    conversion_tests::msg::double__2&& _static_array_with_indexation15);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation15
             * @return Constant reference to member static_array_with_indexation15
             */
            eProsima_user_DllExport const conversion_tests::msg::double__2& static_array_with_indexation15() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation15
             * @return Reference to member static_array_with_indexation15
             */
            eProsima_user_DllExport conversion_tests::msg::double__2& static_array_with_indexation15();
            /*!
             * @brief This function copies the value in member static_array_with_indexation16
             * @param _static_array_with_indexation16 New value to be copied in member static_array_with_indexation16
             */
            eProsima_user_DllExport void static_array_with_indexation16(
                    const conversion_tests::msg::uint8__2& _static_array_with_indexation16);

            /*!
             * @brief This function moves the value in member static_array_with_indexation16
             * @param _static_array_with_indexation16 New value to be moved in member static_array_with_indexation16
             */
            eProsima_user_DllExport void static_array_with_indexation16(
                    conversion_tests::msg::uint8__2&& _static_array_with_indexation16);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation16
             * @return Constant reference to member static_array_with_indexation16
             */
            eProsima_user_DllExport const conversion_tests::msg::uint8__2& static_array_with_indexation16() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation16
             * @return Reference to member static_array_with_indexation16
             */
            eProsima_user_DllExport conversion_tests::msg::uint8__2& static_array_with_indexation16();
            /*!
             * @brief This function copies the value in member static_array_with_indexation17
             * @param _static_array_with_indexation17 New value to be copied in member static_array_with_indexation17
             */
            eProsima_user_DllExport void static_array_with_indexation17(
                    const conversion_tests::msg::string__2& _static_array_with_indexation17);

            /*!
             * @brief This function moves the value in member static_array_with_indexation17
             * @param _static_array_with_indexation17 New value to be moved in member static_array_with_indexation17
             */
            eProsima_user_DllExport void static_array_with_indexation17(
                    conversion_tests::msg::string__2&& _static_array_with_indexation17);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation17
             * @return Constant reference to member static_array_with_indexation17
             */
            eProsima_user_DllExport const conversion_tests::msg::string__2& static_array_with_indexation17() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation17
             * @return Reference to member static_array_with_indexation17
             */
            eProsima_user_DllExport conversion_tests::msg::string__2& static_array_with_indexation17();
            /*!
             * @brief This function copies the value in member static_array_with_indexation18
             * @param _static_array_with_indexation18 New value to be copied in member static_array_with_indexation18
             */
            eProsima_user_DllExport void static_array_with_indexation18(
                    const conversion_tests::msg::wstring__2& _static_array_with_indexation18);

            /*!
             * @brief This function moves the value in member static_array_with_indexation18
             * @param _static_array_with_indexation18 New value to be moved in member static_array_with_indexation18
             */
            eProsima_user_DllExport void static_array_with_indexation18(
                    conversion_tests::msg::wstring__2&& _static_array_with_indexation18);

            /*!
             * @brief This function returns a constant reference to member static_array_with_indexation18
             * @return Constant reference to member static_array_with_indexation18
             */
            eProsima_user_DllExport const conversion_tests::msg::wstring__2& static_array_with_indexation18() const;

            /*!
             * @brief This function returns a reference to member static_array_with_indexation18
             * @return Reference to member static_array_with_indexation18
             */
            eProsima_user_DllExport conversion_tests::msg::wstring__2& static_array_with_indexation18();

            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const conversion_tests::msg::Iec61499Arrayspezifikationen2& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            conversion_tests::msg::boolean__2 m_static_array_with_indexation1;
            conversion_tests::msg::octet__2 m_static_array_with_indexation2;
            conversion_tests::msg::uint16__2 m_static_array_with_indexation3;
            conversion_tests::msg::uint32__2 m_static_array_with_indexation4;
            conversion_tests::msg::uint64__2 m_static_array_with_indexation5;
            conversion_tests::msg::int8__2 m_static_array_with_indexation6;
            conversion_tests::msg::int16__2 m_static_array_with_indexation7;
            conversion_tests::msg::int32__2 m_static_array_with_indexation8;
            conversion_tests::msg::int64__2 m_static_array_with_indexation9;
            conversion_tests::msg::uint8__2 m_static_array_with_indexation10;
            conversion_tests::msg::uint16__2 m_static_array_with_indexation11;
            conversion_tests::msg::uint32__2 m_static_array_with_indexation12;
            conversion_tests::msg::uint64__2 m_static_array_with_indexation13;
            conversion_tests::msg::float__2 m_static_array_with_indexation14;
            conversion_tests::msg::double__2 m_static_array_with_indexation15;
            conversion_tests::msg::uint8__2 m_static_array_with_indexation16;
            conversion_tests::msg::string__2 m_static_array_with_indexation17;
            conversion_tests::msg::wstring__2 m_static_array_with_indexation18;

        };
    } // namespace msg
} // namespace conversion_tests

#endif // _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_IEC61499ARRAYSPEZIFIKATIONEN2_H_

