// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Iec61499Arrayspezifikationen2.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Iec61499Arrayspezifikationen2.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>








#define conversion_tests_msg_Iec61499Arrayspezifikationen2_max_cdr_typesize 2692ULL;














#define conversion_tests_msg_Iec61499Arrayspezifikationen2_max_key_cdr_typesize 0ULL;






















conversion_tests::msg::Iec61499Arrayspezifikationen2::Iec61499Arrayspezifikationen2()
{
    // conversion_tests::msg::boolean__2 m_static_array_with_indexation1
    memset(&m_static_array_with_indexation1, 0, (2) * 1);
    // conversion_tests::msg::octet__2 m_static_array_with_indexation2
    memset(&m_static_array_with_indexation2, 0, (2) * 1);
    // conversion_tests::msg::uint16__2 m_static_array_with_indexation3
    memset(&m_static_array_with_indexation3, 0, (2) * 2);
    // conversion_tests::msg::uint32__2 m_static_array_with_indexation4
    memset(&m_static_array_with_indexation4, 0, (2) * 4);
    // conversion_tests::msg::uint64__2 m_static_array_with_indexation5
    memset(&m_static_array_with_indexation5, 0, (2) * 8);
    // conversion_tests::msg::int8__2 m_static_array_with_indexation6
    memset(&m_static_array_with_indexation6, 0, (2) * 1);
    // conversion_tests::msg::int16__2 m_static_array_with_indexation7
    memset(&m_static_array_with_indexation7, 0, (2) * 2);
    // conversion_tests::msg::int32__2 m_static_array_with_indexation8
    memset(&m_static_array_with_indexation8, 0, (2) * 4);
    // conversion_tests::msg::int64__2 m_static_array_with_indexation9
    memset(&m_static_array_with_indexation9, 0, (2) * 8);
    // conversion_tests::msg::uint8__2 m_static_array_with_indexation10
    memset(&m_static_array_with_indexation10, 0, (2) * 1);
    // conversion_tests::msg::uint16__2 m_static_array_with_indexation11
    memset(&m_static_array_with_indexation11, 0, (2) * 2);
    // conversion_tests::msg::uint32__2 m_static_array_with_indexation12
    memset(&m_static_array_with_indexation12, 0, (2) * 4);
    // conversion_tests::msg::uint64__2 m_static_array_with_indexation13
    memset(&m_static_array_with_indexation13, 0, (2) * 8);
    // conversion_tests::msg::float__2 m_static_array_with_indexation14
    memset(&m_static_array_with_indexation14, 0, (2) * 4);
    // conversion_tests::msg::double__2 m_static_array_with_indexation15
    memset(&m_static_array_with_indexation15, 0, (2) * 8);
    // conversion_tests::msg::uint8__2 m_static_array_with_indexation16
    memset(&m_static_array_with_indexation16, 0, (2) * 1);
    // conversion_tests::msg::string__2 m_static_array_with_indexation17

    // conversion_tests::msg::wstring__2 m_static_array_with_indexation18


}

conversion_tests::msg::Iec61499Arrayspezifikationen2::~Iec61499Arrayspezifikationen2()
{


















}

conversion_tests::msg::Iec61499Arrayspezifikationen2::Iec61499Arrayspezifikationen2(
        const Iec61499Arrayspezifikationen2& x)
{
    m_static_array_with_indexation1 = x.m_static_array_with_indexation1;
    m_static_array_with_indexation2 = x.m_static_array_with_indexation2;
    m_static_array_with_indexation3 = x.m_static_array_with_indexation3;
    m_static_array_with_indexation4 = x.m_static_array_with_indexation4;
    m_static_array_with_indexation5 = x.m_static_array_with_indexation5;
    m_static_array_with_indexation6 = x.m_static_array_with_indexation6;
    m_static_array_with_indexation7 = x.m_static_array_with_indexation7;
    m_static_array_with_indexation8 = x.m_static_array_with_indexation8;
    m_static_array_with_indexation9 = x.m_static_array_with_indexation9;
    m_static_array_with_indexation10 = x.m_static_array_with_indexation10;
    m_static_array_with_indexation11 = x.m_static_array_with_indexation11;
    m_static_array_with_indexation12 = x.m_static_array_with_indexation12;
    m_static_array_with_indexation13 = x.m_static_array_with_indexation13;
    m_static_array_with_indexation14 = x.m_static_array_with_indexation14;
    m_static_array_with_indexation15 = x.m_static_array_with_indexation15;
    m_static_array_with_indexation16 = x.m_static_array_with_indexation16;
    m_static_array_with_indexation17 = x.m_static_array_with_indexation17;
    m_static_array_with_indexation18 = x.m_static_array_with_indexation18;
}

conversion_tests::msg::Iec61499Arrayspezifikationen2::Iec61499Arrayspezifikationen2(
        Iec61499Arrayspezifikationen2&& x) noexcept 
{
    m_static_array_with_indexation1 = std::move(x.m_static_array_with_indexation1);
    m_static_array_with_indexation2 = std::move(x.m_static_array_with_indexation2);
    m_static_array_with_indexation3 = std::move(x.m_static_array_with_indexation3);
    m_static_array_with_indexation4 = std::move(x.m_static_array_with_indexation4);
    m_static_array_with_indexation5 = std::move(x.m_static_array_with_indexation5);
    m_static_array_with_indexation6 = std::move(x.m_static_array_with_indexation6);
    m_static_array_with_indexation7 = std::move(x.m_static_array_with_indexation7);
    m_static_array_with_indexation8 = std::move(x.m_static_array_with_indexation8);
    m_static_array_with_indexation9 = std::move(x.m_static_array_with_indexation9);
    m_static_array_with_indexation10 = std::move(x.m_static_array_with_indexation10);
    m_static_array_with_indexation11 = std::move(x.m_static_array_with_indexation11);
    m_static_array_with_indexation12 = std::move(x.m_static_array_with_indexation12);
    m_static_array_with_indexation13 = std::move(x.m_static_array_with_indexation13);
    m_static_array_with_indexation14 = std::move(x.m_static_array_with_indexation14);
    m_static_array_with_indexation15 = std::move(x.m_static_array_with_indexation15);
    m_static_array_with_indexation16 = std::move(x.m_static_array_with_indexation16);
    m_static_array_with_indexation17 = std::move(x.m_static_array_with_indexation17);
    m_static_array_with_indexation18 = std::move(x.m_static_array_with_indexation18);
}

conversion_tests::msg::Iec61499Arrayspezifikationen2& conversion_tests::msg::Iec61499Arrayspezifikationen2::operator =(
        const Iec61499Arrayspezifikationen2& x)
{

    m_static_array_with_indexation1 = x.m_static_array_with_indexation1;
    m_static_array_with_indexation2 = x.m_static_array_with_indexation2;
    m_static_array_with_indexation3 = x.m_static_array_with_indexation3;
    m_static_array_with_indexation4 = x.m_static_array_with_indexation4;
    m_static_array_with_indexation5 = x.m_static_array_with_indexation5;
    m_static_array_with_indexation6 = x.m_static_array_with_indexation6;
    m_static_array_with_indexation7 = x.m_static_array_with_indexation7;
    m_static_array_with_indexation8 = x.m_static_array_with_indexation8;
    m_static_array_with_indexation9 = x.m_static_array_with_indexation9;
    m_static_array_with_indexation10 = x.m_static_array_with_indexation10;
    m_static_array_with_indexation11 = x.m_static_array_with_indexation11;
    m_static_array_with_indexation12 = x.m_static_array_with_indexation12;
    m_static_array_with_indexation13 = x.m_static_array_with_indexation13;
    m_static_array_with_indexation14 = x.m_static_array_with_indexation14;
    m_static_array_with_indexation15 = x.m_static_array_with_indexation15;
    m_static_array_with_indexation16 = x.m_static_array_with_indexation16;
    m_static_array_with_indexation17 = x.m_static_array_with_indexation17;
    m_static_array_with_indexation18 = x.m_static_array_with_indexation18;

    return *this;
}

conversion_tests::msg::Iec61499Arrayspezifikationen2& conversion_tests::msg::Iec61499Arrayspezifikationen2::operator =(
        Iec61499Arrayspezifikationen2&& x) noexcept
{

    m_static_array_with_indexation1 = std::move(x.m_static_array_with_indexation1);
    m_static_array_with_indexation2 = std::move(x.m_static_array_with_indexation2);
    m_static_array_with_indexation3 = std::move(x.m_static_array_with_indexation3);
    m_static_array_with_indexation4 = std::move(x.m_static_array_with_indexation4);
    m_static_array_with_indexation5 = std::move(x.m_static_array_with_indexation5);
    m_static_array_with_indexation6 = std::move(x.m_static_array_with_indexation6);
    m_static_array_with_indexation7 = std::move(x.m_static_array_with_indexation7);
    m_static_array_with_indexation8 = std::move(x.m_static_array_with_indexation8);
    m_static_array_with_indexation9 = std::move(x.m_static_array_with_indexation9);
    m_static_array_with_indexation10 = std::move(x.m_static_array_with_indexation10);
    m_static_array_with_indexation11 = std::move(x.m_static_array_with_indexation11);
    m_static_array_with_indexation12 = std::move(x.m_static_array_with_indexation12);
    m_static_array_with_indexation13 = std::move(x.m_static_array_with_indexation13);
    m_static_array_with_indexation14 = std::move(x.m_static_array_with_indexation14);
    m_static_array_with_indexation15 = std::move(x.m_static_array_with_indexation15);
    m_static_array_with_indexation16 = std::move(x.m_static_array_with_indexation16);
    m_static_array_with_indexation17 = std::move(x.m_static_array_with_indexation17);
    m_static_array_with_indexation18 = std::move(x.m_static_array_with_indexation18);

    return *this;
}

bool conversion_tests::msg::Iec61499Arrayspezifikationen2::operator ==(
        const Iec61499Arrayspezifikationen2& x) const
{

    return (m_static_array_with_indexation1 == x.m_static_array_with_indexation1 && m_static_array_with_indexation2 == x.m_static_array_with_indexation2 && m_static_array_with_indexation3 == x.m_static_array_with_indexation3 && m_static_array_with_indexation4 == x.m_static_array_with_indexation4 && m_static_array_with_indexation5 == x.m_static_array_with_indexation5 && m_static_array_with_indexation6 == x.m_static_array_with_indexation6 && m_static_array_with_indexation7 == x.m_static_array_with_indexation7 && m_static_array_with_indexation8 == x.m_static_array_with_indexation8 && m_static_array_with_indexation9 == x.m_static_array_with_indexation9 && m_static_array_with_indexation10 == x.m_static_array_with_indexation10 && m_static_array_with_indexation11 == x.m_static_array_with_indexation11 && m_static_array_with_indexation12 == x.m_static_array_with_indexation12 && m_static_array_with_indexation13 == x.m_static_array_with_indexation13 && m_static_array_with_indexation14 == x.m_static_array_with_indexation14 && m_static_array_with_indexation15 == x.m_static_array_with_indexation15 && m_static_array_with_indexation16 == x.m_static_array_with_indexation16 && m_static_array_with_indexation17 == x.m_static_array_with_indexation17 && m_static_array_with_indexation18 == x.m_static_array_with_indexation18);
}

bool conversion_tests::msg::Iec61499Arrayspezifikationen2::operator !=(
        const Iec61499Arrayspezifikationen2& x) const
{
    return !(*this == x);
}

size_t conversion_tests::msg::Iec61499Arrayspezifikationen2::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return conversion_tests_msg_Iec61499Arrayspezifikationen2_max_cdr_typesize;
}

size_t conversion_tests::msg::Iec61499Arrayspezifikationen2::getCdrSerializedSize(
        const conversion_tests::msg::Iec61499Arrayspezifikationen2& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += ((2) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);

    current_alignment += ((2) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);

    current_alignment += ((2) * 2) + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);

    current_alignment += ((2) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += ((2) * 8) + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);

    current_alignment += ((2) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);

    current_alignment += ((2) * 2) + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);

    current_alignment += ((2) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += ((2) * 8) + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);

    current_alignment += ((2) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);

    current_alignment += ((2) * 2) + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);

    current_alignment += ((2) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += ((2) * 8) + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);

    current_alignment += ((2) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += ((2) * 8) + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);

    current_alignment += ((2) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    for(size_t a = 0; a < data.static_array_with_indexation17().size(); ++a)
    {
            current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.static_array_with_indexation17().at(a).size() + 1;

    }

    for(size_t a = 0; a < data.static_array_with_indexation18().size(); ++a)
    {
            current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.static_array_with_indexation18().at(a).size() + 1;

    }

    return current_alignment - initial_alignment;
}

void conversion_tests::msg::Iec61499Arrayspezifikationen2::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_static_array_with_indexation1;

    scdr << m_static_array_with_indexation2;

    scdr << m_static_array_with_indexation3;

    scdr << m_static_array_with_indexation4;

    scdr << m_static_array_with_indexation5;

    scdr << m_static_array_with_indexation6;

    scdr << m_static_array_with_indexation7;

    scdr << m_static_array_with_indexation8;

    scdr << m_static_array_with_indexation9;

    scdr << m_static_array_with_indexation10;

    scdr << m_static_array_with_indexation11;

    scdr << m_static_array_with_indexation12;

    scdr << m_static_array_with_indexation13;

    scdr << m_static_array_with_indexation14;

    scdr << m_static_array_with_indexation15;

    scdr << m_static_array_with_indexation16;

    for (const auto& str : m_static_array_with_indexation17)
    {
        scdr << str.c_str();
    }


    scdr << m_static_array_with_indexation18;


}

void conversion_tests::msg::Iec61499Arrayspezifikationen2::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_static_array_with_indexation1;

    dcdr >> m_static_array_with_indexation2;

    dcdr >> m_static_array_with_indexation3;

    dcdr >> m_static_array_with_indexation4;

    dcdr >> m_static_array_with_indexation5;

    dcdr >> m_static_array_with_indexation6;

    dcdr >> m_static_array_with_indexation7;

    dcdr >> m_static_array_with_indexation8;

    dcdr >> m_static_array_with_indexation9;

    dcdr >> m_static_array_with_indexation10;

    dcdr >> m_static_array_with_indexation11;

    dcdr >> m_static_array_with_indexation12;

    dcdr >> m_static_array_with_indexation13;

    dcdr >> m_static_array_with_indexation14;

    dcdr >> m_static_array_with_indexation15;

    dcdr >> m_static_array_with_indexation16;

    for (auto& str : m_static_array_with_indexation17)
    {
        dcdr >> str;}


    dcdr >> m_static_array_with_indexation18;

}

/*!
 * @brief This function copies the value in member static_array_with_indexation1
 * @param _static_array_with_indexation1 New value to be copied in member static_array_with_indexation1
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation1(
        const conversion_tests::msg::boolean__2& _static_array_with_indexation1)
{
    m_static_array_with_indexation1 = _static_array_with_indexation1;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation1
 * @param _static_array_with_indexation1 New value to be moved in member static_array_with_indexation1
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation1(
        conversion_tests::msg::boolean__2&& _static_array_with_indexation1)
{
    m_static_array_with_indexation1 = std::move(_static_array_with_indexation1);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation1
 * @return Constant reference to member static_array_with_indexation1
 */
const conversion_tests::msg::boolean__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation1() const
{
    return m_static_array_with_indexation1;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation1
 * @return Reference to member static_array_with_indexation1
 */
conversion_tests::msg::boolean__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation1()
{
    return m_static_array_with_indexation1;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation2
 * @param _static_array_with_indexation2 New value to be copied in member static_array_with_indexation2
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation2(
        const conversion_tests::msg::octet__2& _static_array_with_indexation2)
{
    m_static_array_with_indexation2 = _static_array_with_indexation2;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation2
 * @param _static_array_with_indexation2 New value to be moved in member static_array_with_indexation2
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation2(
        conversion_tests::msg::octet__2&& _static_array_with_indexation2)
{
    m_static_array_with_indexation2 = std::move(_static_array_with_indexation2);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation2
 * @return Constant reference to member static_array_with_indexation2
 */
const conversion_tests::msg::octet__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation2() const
{
    return m_static_array_with_indexation2;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation2
 * @return Reference to member static_array_with_indexation2
 */
conversion_tests::msg::octet__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation2()
{
    return m_static_array_with_indexation2;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation3
 * @param _static_array_with_indexation3 New value to be copied in member static_array_with_indexation3
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation3(
        const conversion_tests::msg::uint16__2& _static_array_with_indexation3)
{
    m_static_array_with_indexation3 = _static_array_with_indexation3;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation3
 * @param _static_array_with_indexation3 New value to be moved in member static_array_with_indexation3
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation3(
        conversion_tests::msg::uint16__2&& _static_array_with_indexation3)
{
    m_static_array_with_indexation3 = std::move(_static_array_with_indexation3);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation3
 * @return Constant reference to member static_array_with_indexation3
 */
const conversion_tests::msg::uint16__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation3() const
{
    return m_static_array_with_indexation3;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation3
 * @return Reference to member static_array_with_indexation3
 */
conversion_tests::msg::uint16__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation3()
{
    return m_static_array_with_indexation3;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation4
 * @param _static_array_with_indexation4 New value to be copied in member static_array_with_indexation4
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation4(
        const conversion_tests::msg::uint32__2& _static_array_with_indexation4)
{
    m_static_array_with_indexation4 = _static_array_with_indexation4;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation4
 * @param _static_array_with_indexation4 New value to be moved in member static_array_with_indexation4
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation4(
        conversion_tests::msg::uint32__2&& _static_array_with_indexation4)
{
    m_static_array_with_indexation4 = std::move(_static_array_with_indexation4);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation4
 * @return Constant reference to member static_array_with_indexation4
 */
const conversion_tests::msg::uint32__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation4() const
{
    return m_static_array_with_indexation4;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation4
 * @return Reference to member static_array_with_indexation4
 */
conversion_tests::msg::uint32__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation4()
{
    return m_static_array_with_indexation4;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation5
 * @param _static_array_with_indexation5 New value to be copied in member static_array_with_indexation5
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation5(
        const conversion_tests::msg::uint64__2& _static_array_with_indexation5)
{
    m_static_array_with_indexation5 = _static_array_with_indexation5;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation5
 * @param _static_array_with_indexation5 New value to be moved in member static_array_with_indexation5
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation5(
        conversion_tests::msg::uint64__2&& _static_array_with_indexation5)
{
    m_static_array_with_indexation5 = std::move(_static_array_with_indexation5);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation5
 * @return Constant reference to member static_array_with_indexation5
 */
const conversion_tests::msg::uint64__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation5() const
{
    return m_static_array_with_indexation5;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation5
 * @return Reference to member static_array_with_indexation5
 */
conversion_tests::msg::uint64__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation5()
{
    return m_static_array_with_indexation5;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation6
 * @param _static_array_with_indexation6 New value to be copied in member static_array_with_indexation6
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation6(
        const conversion_tests::msg::int8__2& _static_array_with_indexation6)
{
    m_static_array_with_indexation6 = _static_array_with_indexation6;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation6
 * @param _static_array_with_indexation6 New value to be moved in member static_array_with_indexation6
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation6(
        conversion_tests::msg::int8__2&& _static_array_with_indexation6)
{
    m_static_array_with_indexation6 = std::move(_static_array_with_indexation6);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation6
 * @return Constant reference to member static_array_with_indexation6
 */
const conversion_tests::msg::int8__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation6() const
{
    return m_static_array_with_indexation6;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation6
 * @return Reference to member static_array_with_indexation6
 */
conversion_tests::msg::int8__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation6()
{
    return m_static_array_with_indexation6;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation7
 * @param _static_array_with_indexation7 New value to be copied in member static_array_with_indexation7
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation7(
        const conversion_tests::msg::int16__2& _static_array_with_indexation7)
{
    m_static_array_with_indexation7 = _static_array_with_indexation7;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation7
 * @param _static_array_with_indexation7 New value to be moved in member static_array_with_indexation7
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation7(
        conversion_tests::msg::int16__2&& _static_array_with_indexation7)
{
    m_static_array_with_indexation7 = std::move(_static_array_with_indexation7);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation7
 * @return Constant reference to member static_array_with_indexation7
 */
const conversion_tests::msg::int16__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation7() const
{
    return m_static_array_with_indexation7;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation7
 * @return Reference to member static_array_with_indexation7
 */
conversion_tests::msg::int16__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation7()
{
    return m_static_array_with_indexation7;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation8
 * @param _static_array_with_indexation8 New value to be copied in member static_array_with_indexation8
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation8(
        const conversion_tests::msg::int32__2& _static_array_with_indexation8)
{
    m_static_array_with_indexation8 = _static_array_with_indexation8;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation8
 * @param _static_array_with_indexation8 New value to be moved in member static_array_with_indexation8
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation8(
        conversion_tests::msg::int32__2&& _static_array_with_indexation8)
{
    m_static_array_with_indexation8 = std::move(_static_array_with_indexation8);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation8
 * @return Constant reference to member static_array_with_indexation8
 */
const conversion_tests::msg::int32__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation8() const
{
    return m_static_array_with_indexation8;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation8
 * @return Reference to member static_array_with_indexation8
 */
conversion_tests::msg::int32__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation8()
{
    return m_static_array_with_indexation8;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation9
 * @param _static_array_with_indexation9 New value to be copied in member static_array_with_indexation9
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation9(
        const conversion_tests::msg::int64__2& _static_array_with_indexation9)
{
    m_static_array_with_indexation9 = _static_array_with_indexation9;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation9
 * @param _static_array_with_indexation9 New value to be moved in member static_array_with_indexation9
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation9(
        conversion_tests::msg::int64__2&& _static_array_with_indexation9)
{
    m_static_array_with_indexation9 = std::move(_static_array_with_indexation9);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation9
 * @return Constant reference to member static_array_with_indexation9
 */
const conversion_tests::msg::int64__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation9() const
{
    return m_static_array_with_indexation9;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation9
 * @return Reference to member static_array_with_indexation9
 */
conversion_tests::msg::int64__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation9()
{
    return m_static_array_with_indexation9;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation10
 * @param _static_array_with_indexation10 New value to be copied in member static_array_with_indexation10
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation10(
        const conversion_tests::msg::uint8__2& _static_array_with_indexation10)
{
    m_static_array_with_indexation10 = _static_array_with_indexation10;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation10
 * @param _static_array_with_indexation10 New value to be moved in member static_array_with_indexation10
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation10(
        conversion_tests::msg::uint8__2&& _static_array_with_indexation10)
{
    m_static_array_with_indexation10 = std::move(_static_array_with_indexation10);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation10
 * @return Constant reference to member static_array_with_indexation10
 */
const conversion_tests::msg::uint8__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation10() const
{
    return m_static_array_with_indexation10;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation10
 * @return Reference to member static_array_with_indexation10
 */
conversion_tests::msg::uint8__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation10()
{
    return m_static_array_with_indexation10;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation11
 * @param _static_array_with_indexation11 New value to be copied in member static_array_with_indexation11
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation11(
        const conversion_tests::msg::uint16__2& _static_array_with_indexation11)
{
    m_static_array_with_indexation11 = _static_array_with_indexation11;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation11
 * @param _static_array_with_indexation11 New value to be moved in member static_array_with_indexation11
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation11(
        conversion_tests::msg::uint16__2&& _static_array_with_indexation11)
{
    m_static_array_with_indexation11 = std::move(_static_array_with_indexation11);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation11
 * @return Constant reference to member static_array_with_indexation11
 */
const conversion_tests::msg::uint16__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation11() const
{
    return m_static_array_with_indexation11;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation11
 * @return Reference to member static_array_with_indexation11
 */
conversion_tests::msg::uint16__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation11()
{
    return m_static_array_with_indexation11;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation12
 * @param _static_array_with_indexation12 New value to be copied in member static_array_with_indexation12
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation12(
        const conversion_tests::msg::uint32__2& _static_array_with_indexation12)
{
    m_static_array_with_indexation12 = _static_array_with_indexation12;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation12
 * @param _static_array_with_indexation12 New value to be moved in member static_array_with_indexation12
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation12(
        conversion_tests::msg::uint32__2&& _static_array_with_indexation12)
{
    m_static_array_with_indexation12 = std::move(_static_array_with_indexation12);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation12
 * @return Constant reference to member static_array_with_indexation12
 */
const conversion_tests::msg::uint32__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation12() const
{
    return m_static_array_with_indexation12;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation12
 * @return Reference to member static_array_with_indexation12
 */
conversion_tests::msg::uint32__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation12()
{
    return m_static_array_with_indexation12;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation13
 * @param _static_array_with_indexation13 New value to be copied in member static_array_with_indexation13
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation13(
        const conversion_tests::msg::uint64__2& _static_array_with_indexation13)
{
    m_static_array_with_indexation13 = _static_array_with_indexation13;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation13
 * @param _static_array_with_indexation13 New value to be moved in member static_array_with_indexation13
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation13(
        conversion_tests::msg::uint64__2&& _static_array_with_indexation13)
{
    m_static_array_with_indexation13 = std::move(_static_array_with_indexation13);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation13
 * @return Constant reference to member static_array_with_indexation13
 */
const conversion_tests::msg::uint64__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation13() const
{
    return m_static_array_with_indexation13;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation13
 * @return Reference to member static_array_with_indexation13
 */
conversion_tests::msg::uint64__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation13()
{
    return m_static_array_with_indexation13;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation14
 * @param _static_array_with_indexation14 New value to be copied in member static_array_with_indexation14
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation14(
        const conversion_tests::msg::float__2& _static_array_with_indexation14)
{
    m_static_array_with_indexation14 = _static_array_with_indexation14;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation14
 * @param _static_array_with_indexation14 New value to be moved in member static_array_with_indexation14
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation14(
        conversion_tests::msg::float__2&& _static_array_with_indexation14)
{
    m_static_array_with_indexation14 = std::move(_static_array_with_indexation14);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation14
 * @return Constant reference to member static_array_with_indexation14
 */
const conversion_tests::msg::float__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation14() const
{
    return m_static_array_with_indexation14;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation14
 * @return Reference to member static_array_with_indexation14
 */
conversion_tests::msg::float__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation14()
{
    return m_static_array_with_indexation14;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation15
 * @param _static_array_with_indexation15 New value to be copied in member static_array_with_indexation15
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation15(
        const conversion_tests::msg::double__2& _static_array_with_indexation15)
{
    m_static_array_with_indexation15 = _static_array_with_indexation15;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation15
 * @param _static_array_with_indexation15 New value to be moved in member static_array_with_indexation15
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation15(
        conversion_tests::msg::double__2&& _static_array_with_indexation15)
{
    m_static_array_with_indexation15 = std::move(_static_array_with_indexation15);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation15
 * @return Constant reference to member static_array_with_indexation15
 */
const conversion_tests::msg::double__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation15() const
{
    return m_static_array_with_indexation15;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation15
 * @return Reference to member static_array_with_indexation15
 */
conversion_tests::msg::double__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation15()
{
    return m_static_array_with_indexation15;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation16
 * @param _static_array_with_indexation16 New value to be copied in member static_array_with_indexation16
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation16(
        const conversion_tests::msg::uint8__2& _static_array_with_indexation16)
{
    m_static_array_with_indexation16 = _static_array_with_indexation16;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation16
 * @param _static_array_with_indexation16 New value to be moved in member static_array_with_indexation16
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation16(
        conversion_tests::msg::uint8__2&& _static_array_with_indexation16)
{
    m_static_array_with_indexation16 = std::move(_static_array_with_indexation16);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation16
 * @return Constant reference to member static_array_with_indexation16
 */
const conversion_tests::msg::uint8__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation16() const
{
    return m_static_array_with_indexation16;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation16
 * @return Reference to member static_array_with_indexation16
 */
conversion_tests::msg::uint8__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation16()
{
    return m_static_array_with_indexation16;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation17
 * @param _static_array_with_indexation17 New value to be copied in member static_array_with_indexation17
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation17(
        const conversion_tests::msg::string__2& _static_array_with_indexation17)
{
    m_static_array_with_indexation17 = _static_array_with_indexation17;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation17
 * @param _static_array_with_indexation17 New value to be moved in member static_array_with_indexation17
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation17(
        conversion_tests::msg::string__2&& _static_array_with_indexation17)
{
    m_static_array_with_indexation17 = std::move(_static_array_with_indexation17);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation17
 * @return Constant reference to member static_array_with_indexation17
 */
const conversion_tests::msg::string__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation17() const
{
    return m_static_array_with_indexation17;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation17
 * @return Reference to member static_array_with_indexation17
 */
conversion_tests::msg::string__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation17()
{
    return m_static_array_with_indexation17;
}
/*!
 * @brief This function copies the value in member static_array_with_indexation18
 * @param _static_array_with_indexation18 New value to be copied in member static_array_with_indexation18
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation18(
        const conversion_tests::msg::wstring__2& _static_array_with_indexation18)
{
    m_static_array_with_indexation18 = _static_array_with_indexation18;
}

/*!
 * @brief This function moves the value in member static_array_with_indexation18
 * @param _static_array_with_indexation18 New value to be moved in member static_array_with_indexation18
 */
void conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation18(
        conversion_tests::msg::wstring__2&& _static_array_with_indexation18)
{
    m_static_array_with_indexation18 = std::move(_static_array_with_indexation18);
}

/*!
 * @brief This function returns a constant reference to member static_array_with_indexation18
 * @return Constant reference to member static_array_with_indexation18
 */
const conversion_tests::msg::wstring__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation18() const
{
    return m_static_array_with_indexation18;
}

/*!
 * @brief This function returns a reference to member static_array_with_indexation18
 * @return Reference to member static_array_with_indexation18
 */
conversion_tests::msg::wstring__2& conversion_tests::msg::Iec61499Arrayspezifikationen2::static_array_with_indexation18()
{
    return m_static_array_with_indexation18;
}


size_t conversion_tests::msg::Iec61499Arrayspezifikationen2::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return conversion_tests_msg_Iec61499Arrayspezifikationen2_max_key_cdr_typesize;
}

bool conversion_tests::msg::Iec61499Arrayspezifikationen2::isKeyDefined()
{
    return false;
}

void conversion_tests::msg::Iec61499Arrayspezifikationen2::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



