// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Iec61499PrimitiveDatentypen.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_IEC61499PRIMITIVEDATENTYPEN_H_
#define _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_IEC61499PRIMITIVEDATENTYPEN_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(IEC61499PRIMITIVEDATENTYPEN_SOURCE)
#define IEC61499PRIMITIVEDATENTYPEN_DllAPI __declspec( dllexport )
#else
#define IEC61499PRIMITIVEDATENTYPEN_DllAPI __declspec( dllimport )
#endif // IEC61499PRIMITIVEDATENTYPEN_SOURCE
#else
#define IEC61499PRIMITIVEDATENTYPEN_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define IEC61499PRIMITIVEDATENTYPEN_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace conversion_tests {
    namespace msg {
        /*!
         * @brief This class represents the structure Iec61499PrimitiveDatentypen defined by the user in the IDL file.
         * @ingroup Iec61499PrimitiveDatentypen
         */
        class Iec61499PrimitiveDatentypen
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport Iec61499PrimitiveDatentypen();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~Iec61499PrimitiveDatentypen();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object conversion_tests::msg::Iec61499PrimitiveDatentypen that will be copied.
             */
            eProsima_user_DllExport Iec61499PrimitiveDatentypen(
                    const Iec61499PrimitiveDatentypen& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object conversion_tests::msg::Iec61499PrimitiveDatentypen that will be copied.
             */
            eProsima_user_DllExport Iec61499PrimitiveDatentypen(
                    Iec61499PrimitiveDatentypen&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object conversion_tests::msg::Iec61499PrimitiveDatentypen that will be copied.
             */
            eProsima_user_DllExport Iec61499PrimitiveDatentypen& operator =(
                    const Iec61499PrimitiveDatentypen& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object conversion_tests::msg::Iec61499PrimitiveDatentypen that will be copied.
             */
            eProsima_user_DllExport Iec61499PrimitiveDatentypen& operator =(
                    Iec61499PrimitiveDatentypen&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x conversion_tests::msg::Iec61499PrimitiveDatentypen object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const Iec61499PrimitiveDatentypen& x) const;

            /*!
             * @brief Comparison operator.
             * @param x conversion_tests::msg::Iec61499PrimitiveDatentypen object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const Iec61499PrimitiveDatentypen& x) const;

            /*!
             * @brief This function sets a value in member a_bool
             * @param _a_bool New value for member a_bool
             */
            eProsima_user_DllExport void a_bool(
                    bool _a_bool);

            /*!
             * @brief This function returns the value of member a_bool
             * @return Value of member a_bool
             */
            eProsima_user_DllExport bool a_bool() const;

            /*!
             * @brief This function returns a reference to member a_bool
             * @return Reference to member a_bool
             */
            eProsima_user_DllExport bool& a_bool();

            /*!
             * @brief This function sets a value in member a_byte
             * @param _a_byte New value for member a_byte
             */
            eProsima_user_DllExport void a_byte(
                    uint8_t _a_byte);

            /*!
             * @brief This function returns the value of member a_byte
             * @return Value of member a_byte
             */
            eProsima_user_DllExport uint8_t a_byte() const;

            /*!
             * @brief This function returns a reference to member a_byte
             * @return Reference to member a_byte
             */
            eProsima_user_DllExport uint8_t& a_byte();

            /*!
             * @brief This function sets a value in member a_word
             * @param _a_word New value for member a_word
             */
            eProsima_user_DllExport void a_word(
                    uint16_t _a_word);

            /*!
             * @brief This function returns the value of member a_word
             * @return Value of member a_word
             */
            eProsima_user_DllExport uint16_t a_word() const;

            /*!
             * @brief This function returns a reference to member a_word
             * @return Reference to member a_word
             */
            eProsima_user_DllExport uint16_t& a_word();

            /*!
             * @brief This function sets a value in member a_dword
             * @param _a_dword New value for member a_dword
             */
            eProsima_user_DllExport void a_dword(
                    uint32_t _a_dword);

            /*!
             * @brief This function returns the value of member a_dword
             * @return Value of member a_dword
             */
            eProsima_user_DllExport uint32_t a_dword() const;

            /*!
             * @brief This function returns a reference to member a_dword
             * @return Reference to member a_dword
             */
            eProsima_user_DllExport uint32_t& a_dword();

            /*!
             * @brief This function sets a value in member a_lword
             * @param _a_lword New value for member a_lword
             */
            eProsima_user_DllExport void a_lword(
                    uint64_t _a_lword);

            /*!
             * @brief This function returns the value of member a_lword
             * @return Value of member a_lword
             */
            eProsima_user_DllExport uint64_t a_lword() const;

            /*!
             * @brief This function returns a reference to member a_lword
             * @return Reference to member a_lword
             */
            eProsima_user_DllExport uint64_t& a_lword();

            /*!
             * @brief This function sets a value in member a_sint
             * @param _a_sint New value for member a_sint
             */
            eProsima_user_DllExport void a_sint(
                    int8_t _a_sint);

            /*!
             * @brief This function returns the value of member a_sint
             * @return Value of member a_sint
             */
            eProsima_user_DllExport int8_t a_sint() const;

            /*!
             * @brief This function returns a reference to member a_sint
             * @return Reference to member a_sint
             */
            eProsima_user_DllExport int8_t& a_sint();

            /*!
             * @brief This function sets a value in member a_int
             * @param _a_int New value for member a_int
             */
            eProsima_user_DllExport void a_int(
                    int16_t _a_int);

            /*!
             * @brief This function returns the value of member a_int
             * @return Value of member a_int
             */
            eProsima_user_DllExport int16_t a_int() const;

            /*!
             * @brief This function returns a reference to member a_int
             * @return Reference to member a_int
             */
            eProsima_user_DllExport int16_t& a_int();

            /*!
             * @brief This function sets a value in member a_dint
             * @param _a_dint New value for member a_dint
             */
            eProsima_user_DllExport void a_dint(
                    int32_t _a_dint);

            /*!
             * @brief This function returns the value of member a_dint
             * @return Value of member a_dint
             */
            eProsima_user_DllExport int32_t a_dint() const;

            /*!
             * @brief This function returns a reference to member a_dint
             * @return Reference to member a_dint
             */
            eProsima_user_DllExport int32_t& a_dint();

            /*!
             * @brief This function sets a value in member a_lint
             * @param _a_lint New value for member a_lint
             */
            eProsima_user_DllExport void a_lint(
                    int64_t _a_lint);

            /*!
             * @brief This function returns the value of member a_lint
             * @return Value of member a_lint
             */
            eProsima_user_DllExport int64_t a_lint() const;

            /*!
             * @brief This function returns a reference to member a_lint
             * @return Reference to member a_lint
             */
            eProsima_user_DllExport int64_t& a_lint();

            /*!
             * @brief This function sets a value in member a_usint
             * @param _a_usint New value for member a_usint
             */
            eProsima_user_DllExport void a_usint(
                    uint8_t _a_usint);

            /*!
             * @brief This function returns the value of member a_usint
             * @return Value of member a_usint
             */
            eProsima_user_DllExport uint8_t a_usint() const;

            /*!
             * @brief This function returns a reference to member a_usint
             * @return Reference to member a_usint
             */
            eProsima_user_DllExport uint8_t& a_usint();

            /*!
             * @brief This function sets a value in member a_uint
             * @param _a_uint New value for member a_uint
             */
            eProsima_user_DllExport void a_uint(
                    uint16_t _a_uint);

            /*!
             * @brief This function returns the value of member a_uint
             * @return Value of member a_uint
             */
            eProsima_user_DllExport uint16_t a_uint() const;

            /*!
             * @brief This function returns a reference to member a_uint
             * @return Reference to member a_uint
             */
            eProsima_user_DllExport uint16_t& a_uint();

            /*!
             * @brief This function sets a value in member a_udint
             * @param _a_udint New value for member a_udint
             */
            eProsima_user_DllExport void a_udint(
                    uint32_t _a_udint);

            /*!
             * @brief This function returns the value of member a_udint
             * @return Value of member a_udint
             */
            eProsima_user_DllExport uint32_t a_udint() const;

            /*!
             * @brief This function returns a reference to member a_udint
             * @return Reference to member a_udint
             */
            eProsima_user_DllExport uint32_t& a_udint();

            /*!
             * @brief This function sets a value in member a_ulint
             * @param _a_ulint New value for member a_ulint
             */
            eProsima_user_DllExport void a_ulint(
                    uint64_t _a_ulint);

            /*!
             * @brief This function returns the value of member a_ulint
             * @return Value of member a_ulint
             */
            eProsima_user_DllExport uint64_t a_ulint() const;

            /*!
             * @brief This function returns a reference to member a_ulint
             * @return Reference to member a_ulint
             */
            eProsima_user_DllExport uint64_t& a_ulint();

            /*!
             * @brief This function sets a value in member a_real
             * @param _a_real New value for member a_real
             */
            eProsima_user_DllExport void a_real(
                    float _a_real);

            /*!
             * @brief This function returns the value of member a_real
             * @return Value of member a_real
             */
            eProsima_user_DllExport float a_real() const;

            /*!
             * @brief This function returns a reference to member a_real
             * @return Reference to member a_real
             */
            eProsima_user_DllExport float& a_real();

            /*!
             * @brief This function sets a value in member a_lreal
             * @param _a_lreal New value for member a_lreal
             */
            eProsima_user_DllExport void a_lreal(
                    double _a_lreal);

            /*!
             * @brief This function returns the value of member a_lreal
             * @return Value of member a_lreal
             */
            eProsima_user_DllExport double a_lreal() const;

            /*!
             * @brief This function returns a reference to member a_lreal
             * @return Reference to member a_lreal
             */
            eProsima_user_DllExport double& a_lreal();

            /*!
             * @brief This function sets a value in member a_char
             * @param _a_char New value for member a_char
             */
            eProsima_user_DllExport void a_char(
                    uint8_t _a_char);

            /*!
             * @brief This function returns the value of member a_char
             * @return Value of member a_char
             */
            eProsima_user_DllExport uint8_t a_char() const;

            /*!
             * @brief This function returns a reference to member a_char
             * @return Reference to member a_char
             */
            eProsima_user_DllExport uint8_t& a_char();

            /*!
             * @brief This function copies the value in member a_string
             * @param _a_string New value to be copied in member a_string
             */
            eProsima_user_DllExport void a_string(
                    const std::string& _a_string);

            /*!
             * @brief This function moves the value in member a_string
             * @param _a_string New value to be moved in member a_string
             */
            eProsima_user_DllExport void a_string(
                    std::string&& _a_string);

            /*!
             * @brief This function returns a constant reference to member a_string
             * @return Constant reference to member a_string
             */
            eProsima_user_DllExport const std::string& a_string() const;

            /*!
             * @brief This function returns a reference to member a_string
             * @return Reference to member a_string
             */
            eProsima_user_DllExport std::string& a_string();
            /*!
             * @brief This function copies the value in member a_bound_string
             * @param _a_bound_string New value to be copied in member a_bound_string
             */
            eProsima_user_DllExport void a_bound_string(
                    const eprosima::fastrtps::fixed_string<2>& _a_bound_string);

            /*!
             * @brief This function moves the value in member a_bound_string
             * @param _a_bound_string New value to be moved in member a_bound_string
             */
            eProsima_user_DllExport void a_bound_string(
                    eprosima::fastrtps::fixed_string<2>&& _a_bound_string);

            /*!
             * @brief This function returns a constant reference to member a_bound_string
             * @return Constant reference to member a_bound_string
             */
            eProsima_user_DllExport const eprosima::fastrtps::fixed_string<2>& a_bound_string() const;

            /*!
             * @brief This function returns a reference to member a_bound_string
             * @return Reference to member a_bound_string
             */
            eProsima_user_DllExport eprosima::fastrtps::fixed_string<2>& a_bound_string();
            /*!
             * @brief This function copies the value in member a_wstring
             * @param _a_wstring New value to be copied in member a_wstring
             */
            eProsima_user_DllExport void a_wstring(
                    const std::wstring& _a_wstring);

            /*!
             * @brief This function moves the value in member a_wstring
             * @param _a_wstring New value to be moved in member a_wstring
             */
            eProsima_user_DllExport void a_wstring(
                    std::wstring&& _a_wstring);

            /*!
             * @brief This function returns a constant reference to member a_wstring
             * @return Constant reference to member a_wstring
             */
            eProsima_user_DllExport const std::wstring& a_wstring() const;

            /*!
             * @brief This function returns a reference to member a_wstring
             * @return Reference to member a_wstring
             */
            eProsima_user_DllExport std::wstring& a_wstring();
            /*!
             * @brief This function copies the value in member a_bound_wstring
             * @param _a_bound_wstring New value to be copied in member a_bound_wstring
             */
            eProsima_user_DllExport void a_bound_wstring(
                    const std::wstring& _a_bound_wstring);

            /*!
             * @brief This function moves the value in member a_bound_wstring
             * @param _a_bound_wstring New value to be moved in member a_bound_wstring
             */
            eProsima_user_DllExport void a_bound_wstring(
                    std::wstring&& _a_bound_wstring);

            /*!
             * @brief This function returns a constant reference to member a_bound_wstring
             * @return Constant reference to member a_bound_wstring
             */
            eProsima_user_DllExport const std::wstring& a_bound_wstring() const;

            /*!
             * @brief This function returns a reference to member a_bound_wstring
             * @return Reference to member a_bound_wstring
             */
            eProsima_user_DllExport std::wstring& a_bound_wstring();

            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const conversion_tests::msg::Iec61499PrimitiveDatentypen& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            bool m_a_bool;
            uint8_t m_a_byte;
            uint16_t m_a_word;
            uint32_t m_a_dword;
            uint64_t m_a_lword;
            int8_t m_a_sint;
            int16_t m_a_int;
            int32_t m_a_dint;
            int64_t m_a_lint;
            uint8_t m_a_usint;
            uint16_t m_a_uint;
            uint32_t m_a_udint;
            uint64_t m_a_ulint;
            float m_a_real;
            double m_a_lreal;
            uint8_t m_a_char;
            std::string m_a_string;
            eprosima::fastrtps::fixed_string<2> m_a_bound_string;
            std::wstring m_a_wstring;
            std::wstring m_a_bound_wstring;

        };
    } // namespace msg
} // namespace conversion_tests

#endif // _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_IEC61499PRIMITIVEDATENTYPEN_H_

