// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Ros2PrimitiveDatentypen.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_ROS2PRIMITIVEDATENTYPEN_H_
#define _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_ROS2PRIMITIVEDATENTYPEN_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ROS2PRIMITIVEDATENTYPEN_SOURCE)
#define ROS2PRIMITIVEDATENTYPEN_DllAPI __declspec( dllexport )
#else
#define ROS2PRIMITIVEDATENTYPEN_DllAPI __declspec( dllimport )
#endif // ROS2PRIMITIVEDATENTYPEN_SOURCE
#else
#define ROS2PRIMITIVEDATENTYPEN_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ROS2PRIMITIVEDATENTYPEN_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace conversion_tests {
    namespace msg {
        /*!
         * @brief This class represents the structure Ros2PrimitiveDatentypen defined by the user in the IDL file.
         * @ingroup Ros2PrimitiveDatentypen
         */
        class Ros2PrimitiveDatentypen
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport Ros2PrimitiveDatentypen();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~Ros2PrimitiveDatentypen();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object conversion_tests::msg::Ros2PrimitiveDatentypen that will be copied.
             */
            eProsima_user_DllExport Ros2PrimitiveDatentypen(
                    const Ros2PrimitiveDatentypen& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object conversion_tests::msg::Ros2PrimitiveDatentypen that will be copied.
             */
            eProsima_user_DllExport Ros2PrimitiveDatentypen(
                    Ros2PrimitiveDatentypen&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object conversion_tests::msg::Ros2PrimitiveDatentypen that will be copied.
             */
            eProsima_user_DllExport Ros2PrimitiveDatentypen& operator =(
                    const Ros2PrimitiveDatentypen& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object conversion_tests::msg::Ros2PrimitiveDatentypen that will be copied.
             */
            eProsima_user_DllExport Ros2PrimitiveDatentypen& operator =(
                    Ros2PrimitiveDatentypen&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x conversion_tests::msg::Ros2PrimitiveDatentypen object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const Ros2PrimitiveDatentypen& x) const;

            /*!
             * @brief Comparison operator.
             * @param x conversion_tests::msg::Ros2PrimitiveDatentypen object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const Ros2PrimitiveDatentypen& x) const;

            /*!
             * @brief This function sets a value in member a_bool
             * @param _a_bool New value for member a_bool
             */
            eProsima_user_DllExport void a_bool(
                    bool _a_bool);

            /*!
             * @brief This function returns the value of member a_bool
             * @return Value of member a_bool
             */
            eProsima_user_DllExport bool a_bool() const;

            /*!
             * @brief This function returns a reference to member a_bool
             * @return Reference to member a_bool
             */
            eProsima_user_DllExport bool& a_bool();

            /*!
             * @brief This function sets a value in member a_byte
             * @param _a_byte New value for member a_byte
             */
            eProsima_user_DllExport void a_byte(
                    uint8_t _a_byte);

            /*!
             * @brief This function returns the value of member a_byte
             * @return Value of member a_byte
             */
            eProsima_user_DllExport uint8_t a_byte() const;

            /*!
             * @brief This function returns a reference to member a_byte
             * @return Reference to member a_byte
             */
            eProsima_user_DllExport uint8_t& a_byte();

            /*!
             * @brief This function sets a value in member a_uint8
             * @param _a_uint8 New value for member a_uint8
             */
            eProsima_user_DllExport void a_uint8(
                    uint8_t _a_uint8);

            /*!
             * @brief This function returns the value of member a_uint8
             * @return Value of member a_uint8
             */
            eProsima_user_DllExport uint8_t a_uint8() const;

            /*!
             * @brief This function returns a reference to member a_uint8
             * @return Reference to member a_uint8
             */
            eProsima_user_DllExport uint8_t& a_uint8();

            /*!
             * @brief This function sets a value in member a_uint16
             * @param _a_uint16 New value for member a_uint16
             */
            eProsima_user_DllExport void a_uint16(
                    uint16_t _a_uint16);

            /*!
             * @brief This function returns the value of member a_uint16
             * @return Value of member a_uint16
             */
            eProsima_user_DllExport uint16_t a_uint16() const;

            /*!
             * @brief This function returns a reference to member a_uint16
             * @return Reference to member a_uint16
             */
            eProsima_user_DllExport uint16_t& a_uint16();

            /*!
             * @brief This function sets a value in member a_uint32
             * @param _a_uint32 New value for member a_uint32
             */
            eProsima_user_DllExport void a_uint32(
                    uint32_t _a_uint32);

            /*!
             * @brief This function returns the value of member a_uint32
             * @return Value of member a_uint32
             */
            eProsima_user_DllExport uint32_t a_uint32() const;

            /*!
             * @brief This function returns a reference to member a_uint32
             * @return Reference to member a_uint32
             */
            eProsima_user_DllExport uint32_t& a_uint32();

            /*!
             * @brief This function sets a value in member a_uint64
             * @param _a_uint64 New value for member a_uint64
             */
            eProsima_user_DllExport void a_uint64(
                    uint64_t _a_uint64);

            /*!
             * @brief This function returns the value of member a_uint64
             * @return Value of member a_uint64
             */
            eProsima_user_DllExport uint64_t a_uint64() const;

            /*!
             * @brief This function returns a reference to member a_uint64
             * @return Reference to member a_uint64
             */
            eProsima_user_DllExport uint64_t& a_uint64();

            /*!
             * @brief This function sets a value in member a_int8
             * @param _a_int8 New value for member a_int8
             */
            eProsima_user_DllExport void a_int8(
                    int8_t _a_int8);

            /*!
             * @brief This function returns the value of member a_int8
             * @return Value of member a_int8
             */
            eProsima_user_DllExport int8_t a_int8() const;

            /*!
             * @brief This function returns a reference to member a_int8
             * @return Reference to member a_int8
             */
            eProsima_user_DllExport int8_t& a_int8();

            /*!
             * @brief This function sets a value in member a_int16
             * @param _a_int16 New value for member a_int16
             */
            eProsima_user_DllExport void a_int16(
                    int16_t _a_int16);

            /*!
             * @brief This function returns the value of member a_int16
             * @return Value of member a_int16
             */
            eProsima_user_DllExport int16_t a_int16() const;

            /*!
             * @brief This function returns a reference to member a_int16
             * @return Reference to member a_int16
             */
            eProsima_user_DllExport int16_t& a_int16();

            /*!
             * @brief This function sets a value in member a_int32
             * @param _a_int32 New value for member a_int32
             */
            eProsima_user_DllExport void a_int32(
                    int32_t _a_int32);

            /*!
             * @brief This function returns the value of member a_int32
             * @return Value of member a_int32
             */
            eProsima_user_DllExport int32_t a_int32() const;

            /*!
             * @brief This function returns a reference to member a_int32
             * @return Reference to member a_int32
             */
            eProsima_user_DllExport int32_t& a_int32();

            /*!
             * @brief This function sets a value in member a_int64
             * @param _a_int64 New value for member a_int64
             */
            eProsima_user_DllExport void a_int64(
                    int64_t _a_int64);

            /*!
             * @brief This function returns the value of member a_int64
             * @return Value of member a_int64
             */
            eProsima_user_DllExport int64_t a_int64() const;

            /*!
             * @brief This function returns a reference to member a_int64
             * @return Reference to member a_int64
             */
            eProsima_user_DllExport int64_t& a_int64();

            /*!
             * @brief This function sets a value in member a_float32
             * @param _a_float32 New value for member a_float32
             */
            eProsima_user_DllExport void a_float32(
                    float _a_float32);

            /*!
             * @brief This function returns the value of member a_float32
             * @return Value of member a_float32
             */
            eProsima_user_DllExport float a_float32() const;

            /*!
             * @brief This function returns a reference to member a_float32
             * @return Reference to member a_float32
             */
            eProsima_user_DllExport float& a_float32();

            /*!
             * @brief This function sets a value in member a_float64
             * @param _a_float64 New value for member a_float64
             */
            eProsima_user_DllExport void a_float64(
                    double _a_float64);

            /*!
             * @brief This function returns the value of member a_float64
             * @return Value of member a_float64
             */
            eProsima_user_DllExport double a_float64() const;

            /*!
             * @brief This function returns a reference to member a_float64
             * @return Reference to member a_float64
             */
            eProsima_user_DllExport double& a_float64();

            /*!
             * @brief This function sets a value in member a_char
             * @param _a_char New value for member a_char
             */
            eProsima_user_DllExport void a_char(
                    uint8_t _a_char);

            /*!
             * @brief This function returns the value of member a_char
             * @return Value of member a_char
             */
            eProsima_user_DllExport uint8_t a_char() const;

            /*!
             * @brief This function returns a reference to member a_char
             * @return Reference to member a_char
             */
            eProsima_user_DllExport uint8_t& a_char();

            /*!
             * @brief This function copies the value in member a_string
             * @param _a_string New value to be copied in member a_string
             */
            eProsima_user_DllExport void a_string(
                    const std::string& _a_string);

            /*!
             * @brief This function moves the value in member a_string
             * @param _a_string New value to be moved in member a_string
             */
            eProsima_user_DllExport void a_string(
                    std::string&& _a_string);

            /*!
             * @brief This function returns a constant reference to member a_string
             * @return Constant reference to member a_string
             */
            eProsima_user_DllExport const std::string& a_string() const;

            /*!
             * @brief This function returns a reference to member a_string
             * @return Reference to member a_string
             */
            eProsima_user_DllExport std::string& a_string();
            /*!
             * @brief This function copies the value in member a_bound_string
             * @param _a_bound_string New value to be copied in member a_bound_string
             */
            eProsima_user_DllExport void a_bound_string(
                    const eprosima::fastrtps::fixed_string<2>& _a_bound_string);

            /*!
             * @brief This function moves the value in member a_bound_string
             * @param _a_bound_string New value to be moved in member a_bound_string
             */
            eProsima_user_DllExport void a_bound_string(
                    eprosima::fastrtps::fixed_string<2>&& _a_bound_string);

            /*!
             * @brief This function returns a constant reference to member a_bound_string
             * @return Constant reference to member a_bound_string
             */
            eProsima_user_DllExport const eprosima::fastrtps::fixed_string<2>& a_bound_string() const;

            /*!
             * @brief This function returns a reference to member a_bound_string
             * @return Reference to member a_bound_string
             */
            eProsima_user_DllExport eprosima::fastrtps::fixed_string<2>& a_bound_string();
            /*!
             * @brief This function copies the value in member a_wstring
             * @param _a_wstring New value to be copied in member a_wstring
             */
            eProsima_user_DllExport void a_wstring(
                    const std::wstring& _a_wstring);

            /*!
             * @brief This function moves the value in member a_wstring
             * @param _a_wstring New value to be moved in member a_wstring
             */
            eProsima_user_DllExport void a_wstring(
                    std::wstring&& _a_wstring);

            /*!
             * @brief This function returns a constant reference to member a_wstring
             * @return Constant reference to member a_wstring
             */
            eProsima_user_DllExport const std::wstring& a_wstring() const;

            /*!
             * @brief This function returns a reference to member a_wstring
             * @return Reference to member a_wstring
             */
            eProsima_user_DllExport std::wstring& a_wstring();
            /*!
             * @brief This function copies the value in member a_bound_wstring
             * @param _a_bound_wstring New value to be copied in member a_bound_wstring
             */
            eProsima_user_DllExport void a_bound_wstring(
                    const std::wstring& _a_bound_wstring);

            /*!
             * @brief This function moves the value in member a_bound_wstring
             * @param _a_bound_wstring New value to be moved in member a_bound_wstring
             */
            eProsima_user_DllExport void a_bound_wstring(
                    std::wstring&& _a_bound_wstring);

            /*!
             * @brief This function returns a constant reference to member a_bound_wstring
             * @return Constant reference to member a_bound_wstring
             */
            eProsima_user_DllExport const std::wstring& a_bound_wstring() const;

            /*!
             * @brief This function returns a reference to member a_bound_wstring
             * @return Reference to member a_bound_wstring
             */
            eProsima_user_DllExport std::wstring& a_bound_wstring();

            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const conversion_tests::msg::Ros2PrimitiveDatentypen& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            bool m_a_bool;
            uint8_t m_a_byte;
            uint8_t m_a_uint8;
            uint16_t m_a_uint16;
            uint32_t m_a_uint32;
            uint64_t m_a_uint64;
            int8_t m_a_int8;
            int16_t m_a_int16;
            int32_t m_a_int32;
            int64_t m_a_int64;
            float m_a_float32;
            double m_a_float64;
            uint8_t m_a_char;
            std::string m_a_string;
            eprosima::fastrtps::fixed_string<2> m_a_bound_string;
            std::wstring m_a_wstring;
            std::wstring m_a_bound_wstring;

        };
    } // namespace msg
} // namespace conversion_tests

#endif // _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_ROS2PRIMITIVEDATENTYPEN_H_

