// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Ros2Konstanten.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Ros2Konstanten.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define conversion_tests_msg_Ros2Konstanten_max_cdr_typesize 1ULL;
#define conversion_tests_msg_Ros2Konstanten_max_key_cdr_typesize 0ULL;


conversion_tests::msg::Ros2Konstanten::Ros2Konstanten()
{
    // uint8 m_structure_needs_at_least_one_member
    m_structure_needs_at_least_one_member = 0;

}

conversion_tests::msg::Ros2Konstanten::~Ros2Konstanten()
{
}

conversion_tests::msg::Ros2Konstanten::Ros2Konstanten(
        const Ros2Konstanten& x)
{
    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;
}

conversion_tests::msg::Ros2Konstanten::Ros2Konstanten(
        Ros2Konstanten&& x) noexcept 
{
    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;
}

conversion_tests::msg::Ros2Konstanten& conversion_tests::msg::Ros2Konstanten::operator =(
        const Ros2Konstanten& x)
{

    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;

    return *this;
}

conversion_tests::msg::Ros2Konstanten& conversion_tests::msg::Ros2Konstanten::operator =(
        Ros2Konstanten&& x) noexcept
{

    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;

    return *this;
}

bool conversion_tests::msg::Ros2Konstanten::operator ==(
        const Ros2Konstanten& x) const
{

    return (m_structure_needs_at_least_one_member == x.m_structure_needs_at_least_one_member);
}

bool conversion_tests::msg::Ros2Konstanten::operator !=(
        const Ros2Konstanten& x) const
{
    return !(*this == x);
}

size_t conversion_tests::msg::Ros2Konstanten::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return conversion_tests_msg_Ros2Konstanten_max_cdr_typesize;
}

size_t conversion_tests::msg::Ros2Konstanten::getCdrSerializedSize(
        const conversion_tests::msg::Ros2Konstanten& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

void conversion_tests::msg::Ros2Konstanten::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_structure_needs_at_least_one_member;

}

void conversion_tests::msg::Ros2Konstanten::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_structure_needs_at_least_one_member;
}

/*!
 * @brief This function sets a value in member structure_needs_at_least_one_member
 * @param _structure_needs_at_least_one_member New value for member structure_needs_at_least_one_member
 */
void conversion_tests::msg::Ros2Konstanten::structure_needs_at_least_one_member(
        uint8_t _structure_needs_at_least_one_member)
{
    m_structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
}

/*!
 * @brief This function returns the value of member structure_needs_at_least_one_member
 * @return Value of member structure_needs_at_least_one_member
 */
uint8_t conversion_tests::msg::Ros2Konstanten::structure_needs_at_least_one_member() const
{
    return m_structure_needs_at_least_one_member;
}

/*!
 * @brief This function returns a reference to member structure_needs_at_least_one_member
 * @return Reference to member structure_needs_at_least_one_member
 */
uint8_t& conversion_tests::msg::Ros2Konstanten::structure_needs_at_least_one_member()
{
    return m_structure_needs_at_least_one_member;
}



size_t conversion_tests::msg::Ros2Konstanten::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return conversion_tests_msg_Ros2Konstanten_max_key_cdr_typesize;
}

bool conversion_tests::msg::Ros2Konstanten::isKeyDefined()
{
    return false;
}

void conversion_tests::msg::Ros2Konstanten::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



