bool[2] static_array_with_indexation1 // @IEC61499_StartIndex(-1).
byte[2] static_array_with_indexation2 // @IEC61499_StartIndex(-1).
uint16[2] static_array_with_indexation3 // @IEC61499_WORD, @IEC61499_StartIndex(-1).
uint32[2] static_array_with_indexation4 // @IEC61499_DWORD, @IEC61499_StartIndex(-1).
uint64[2] static_array_with_indexation5 // @IEC61499_LWORD, @IEC61499_StartIndex(-1).
int8[2] static_array_with_indexation6 // @IEC61499_StartIndex(-1).
int16[2] static_array_with_indexation7 // @IEC61499_StartIndex(-1).
int32[2] static_array_with_indexation8 // @IEC61499_StartIndex(-1).
int64[2] static_array_with_indexation9 // @IEC61499_StartIndex(-1).
uint8[2] static_array_with_indexation10 // @IEC61499_StartIndex(-1).
uint16[2] static_array_with_indexation11 // @IEC61499_StartIndex(-1).
uint32[2] static_array_with_indexation12 // @IEC61499_StartIndex(-1).
uint64[2] static_array_with_indexation13 // @IEC61499_StartIndex(-1).
float32[2] static_array_with_indexation14 // @IEC61499_StartIndex(-1).
float64[2] static_array_with_indexation15 // @IEC61499_StartIndex(-1).
char[2] static_array_with_indexation16 // @IEC61499_StartIndex(-1).
string[2] static_array_with_indexation17 // @IEC61499_StartIndex(-1).
wstring[2] static_array_with_indexation18 // @IEC61499_StartIndex(-1).
