int8[2] dec_sint_array [1,2] # @IEC61499_StartIndex(-1).
int8[2] bin_sint_array [0b0,0b1] # @IEC61499_StartIndex(-1).
int8[2] oct_sint_array [0o1,0o2] # @IEC61499_StartIndex(-1).
int8[2] hex_sint_array [0x1,0x2] # @IEC61499_StartIndex(-1).
bool[2] int_bool_array [0,1] # @IEC61499_StartIndex(-1).
bool[2] string_bool_array [false,true] # @IEC61499_StartIndex(-1).
char[2] char_hex_array [0x41,0x42] # @IEC61499_StartIndex(-1).
string[2] special_string_array [" aA1&"," aA2&"] # @IEC61499_StartIndex(-1).
string[2] space_string_array [" "," "] # @IEC61499_StartIndex(-1).
float32[2] a_real_array [0.1,0.2] # @IEC61499_StartIndex(-1).
