int32 an_int=1
string a_string "hello \"some\" world"
float32 a_float32 0.32
float64 a_float64 0.64
int32[] unbounded_integer_array [1,2,3,4]
int32[5] five_integers_array
int32[<=5] up_to_five_integers_array
string string_of_unbounded_size
string<=10 up_to_ten_characters_string
string[<=5] up_to_five_unbounded_strings
string<=10[] unbounded_array_of_strings_up_to_ten_characters_each
string<=10[<=5] up_to_five_strings_up_to_ten_characters_each
another_pkg/YetAnotherMessage val